INSERT INTO approval_opinions VALUES (0,1,1,1)
INSERT INTO approval_opinions VALUES (0,2,1,1)
INSERT INTO approval_opinions VALUES (0,3,1,1)
INSERT INTO approval_opinions VALUES (0,4,1,1)
INSERT INTO approval_opinions VALUES (0,5,1,1)
INSERT INTO approval_opinions VALUES (0,6,1,1)
INSERT INTO approval_opinions VALUES (0,7,1,1)
INSERT INTO approval_opinions VALUES (0,8,1,1)
INSERT INTO approval_opinions VALUES (0,9,1,1)
INSERT INTO approval_opinions VALUES (0,10,1,1)
INSERT INTO approval_opinions VALUES (0,11,1,1)

