INSERT INTO order_forms	VALUES (0,'计算机','计算机组成原理','计算机组成原理','中国农业大学出版社',100,1)
INSERT INTO order_forms	VALUES (0,'计算机','计算机网络','计算机网络基础','哈尔滨工程大学出版社',100,1)
INSERT INTO order_forms	VALUES (0,'计算机','计算机组成原理','计算机组成原理','中国农业大学出版社',100,1)
INSERT INTO order_forms	VALUES (0,'计算机','形势与政策','时事报告大学生版','中宣部时事报告社',100,1)
INSERT INTO order_forms	VALUES (0,'计算机','毛泽东思想和中国特色社会主义理论体系概论','毛泽东思想和中国特色社会主义理论体系概论：2021年版','高等教育出版社',100,1)
INSERT INTO order_forms	VALUES (0,'计算机','中国特色社会主义理论教育实践','中国特色社会主义理论教育实践','中国农业出版社',100,1)
INSERT INTO order_forms	VALUES (0,'计算机','Python语言程序设计','Python语言程序设计基础','高等教育出版社',100,1)
INSERT INTO order_forms VALUES (0,'计算机','Linux 操作系统','Linux操作系统','电子工业出版社',100,1)
INSERT INTO order_forms	VALUES (0,'计算机','Java高级编程及应用','Java高级特性编程及实战','人民邮电出版社',100,1)
INSERT INTO order_forms VALUES (0,'计算机','IT项目管理','IT项目管理（第2版）','人民邮电出版社',100,1)
INSERT INTO order_forms VALUES (0,'计算机','Java面向对象程序设计','Java语言程序设计','电子工业出版社',100,1)